### ISSUE TITLE
#Suggestion Use Alpine for lower space usage #2

### ISSUE THREAD

**Issue by lilkidsuave** [waschinski/cosmos-cert-extractor#4]
Title. Alpine images are 2x smaller than debian slim.

**Comment by waschinski** [comment]
Thanks for the suggestion. While I generally agree and also prefer using alpine images I am not completely sure in combination with Python.

If I remember correctly I once ran into problems and came across this article https://pythonspeed.com/articles/alpine-docker-python/ which might be outdated though. I might have to just give it a go for this little project and see for myself.

**Comment by lilkidsuave** [comment]
My alpine branch works fine with it.
https://github.com/lilkidsuave/cosmos-cert-extractor/tree/alpine

And if you are still iffy, someone in the discord also showed me a simpler bash version, and I took it further here.
https://github.com/lilkidsuave/cosmos-cert-extractor/tree/Bash

**Comment by lilkidsuave** [comment]
> Thanks for the suggestion. While I generally agree and also prefer using alpine images I am not completely sure in combination with Python.
> 
> If I remember correctly I once ran into problems and came across this article https://pythonspeed.com/articles/alpine-docker-python/ which might be outdated though. I might have to just give it a go for this little project and see for myself.

Regarding build speed, its not far off debian, but Bash is much faster.
![Screenshot_20240625_220702_Brave](https://github.com/waschinski/cosmos-cert-extractor/assets/66171643/0b9101ce-5ed1-4d4e-97a7-2a8121a73641)

**Comment by waschinski** [comment]
Yeah I saw the comment on Discord. It's pretty slick doing it in Bash tbh. I am wondering if `inotifywait` is also triggering multiple times on the file modification like when using watchdog, but you didn't opt for a file size check, so I assume it does not?

Anyway, I gave the alpine image a spin and as expected the image size is significantly lower. It seems to use a couple MB more RAM (approx. 17MB vs 11MB) though.

**Comment by lilkidsuave** [comment]
> Yeah I saw the comment on Discord. It's pretty slick doing it in Bash tbh. I am wondering if `inotifywait` is also triggering multiple times on the file modification like when using watchdog, but you didn't opt for a file size check, so I assume it does not?
> 
> Anyway, I gave the alpine image a spin and as expected the image size is significantly lower. It seems to use a couple MB more RAM (approx. 17MB vs 11MB) though.

It doesn't double renew, but it does clog the logs when the config file gets changed.
![Screenshot_20240626_174609_Brave](https://github.com/waschinski/cosmos-cert-extractor/assets/66171643/f9617cfe-2ecb-4374-a305-c2b1bd0214ab)

**Comment by lilkidsuave** [comment]
> Anyway, I gave the alpine image a spin and as expected the image size is significantly lower. It seems to use a couple MB more RAM (approx. 17MB vs 11MB) though.

The true savings is in the Bash method.
![Screenshot_20240626_174917_Brave](https://github.com/waschinski/cosmos-cert-extractor/assets/66171643/5a155ea6-496f-40bf-b292-6cd351ac3c46)

**Comment by waschinski** [comment]
> The true savings is in the Bash method.

Now that's some small memory footprint!

> It doesn't double renew, but it does clog the logs when the config file gets changed.

You could try specifying `-q` twice as then _"the program will output nothing at all, except in the case of fatal errors."_

**Comment by lilkidsuave** [comment]
Thats true. Honestly that feature is already baked into the logs viewer anyway, it was just a concern of mine.

**Comment by lilkidsuave** [comment]
Closing as main issue is complete.
